### ISSUE TITLE
Consider including DRMAA support

### ISSUE THREAD

**Issue by pvanheus** [SANBI-SA/ansible-role-slurm#6]
A role for SLURM DRMAA support is here:

https://github.com/SANBI-SA/ansible-role-slurm-drmaa

It compiles and installs the DRMAA module from source. While this is an independent source tree compared to the main Slurm one, it uses variables from the Slurm role to configure the DRMAA module and thus depends on the settings of the Slurm role.

**Comment by Banshee1221** [comment]
Work on merging the [](https://github.com/SANBI-SA/ansible-role-slurm-drmaa)
